version: "3"
services:

  # postgres database
  db:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: townhall
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - townhalldb-app-db-data:/var/lib/postgresql/data/  # persist data even if container shuts down
      - ./db_init_scripts:/docker-entrypoint-initdb.d/  # schema creation
    ports:
      - "5432:5432"

volumes:
  townhalldb-app-db-data:
