version: "3"
services:

  # postgres database
  db:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: townhalldb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - townhalldb-app-db-data:/var/lib/postgresql/data/  # persist data even if container shuts down
      - ./db_init_scripts:/docker-entrypoint-initdb.d/  # schema creation
    ports:
      - "5432:5432"
  
  # To add the above postgres server to pgadmin, use hostname as defined by docker: 'postgres'
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@townhall.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:app-pgsql-server"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  
volumes:
  townhalldb-app-db-data:
  pgadmin-data:
